### PR TITLE
Error

### PR DESCRIPTION
**Pull request by LySoon**
image

im using %100 Vanilla version of the resource

### CODE REVIEW

**Comment by xander1998** [comment]
I will not be merging this due to the ESX portion. If you want the ESX version to be released I will take your fork @lenzh and put it on my public forum topic for you to support.

Respond here with your answer

**Comment by xander1998** [comment]
@LySoon I don't understand the issue you are having as there is no error information there. Also I am not sure why its showing es_extended stuff since my resource doesn't have ESX. If you are adding ESX to your resource then I can't help you.

**Comment by LySoon** [comment]
Yea i would like to use this resource

Thanks ^^


İ have tried to trigger it as a ESX Usable item and only for police job ^^

**Comment by xander1998** [comment]
This resource does not support ESX. If you want it to support ESX then write the ESX code and use it on your server. I do not support ESX and NEVER will.

**Pull request closed without merging**
